/* POSTS TABLE */
CREATE TABLE posts(
   id SERIAL PRIMARY KEY,
   title VARCHAR(50) NOT NULL,
   content TEXT NOT NULL,
   published BOOLEAN NOT NULL DEFAULT 'f',
   created_at TIMESTAMPTZ NOT NULL DEFAULT Now()
);